"""
AGENT 50 - FILE MANAGEMENT INTERFACE
Agent50 کے لیے مرکزی فائل لکھنے کا سسٹم
"""

from pathlib import Path
from auto_save_system import save_file, list_project_files

class AgentFileClient:
    """Agent50 فائل لکھنے کا مرکزی انٹرفیس"""

    def __init__(self, project_name: str):
        self.project = project_name

    def write(self, relative_path: str, content: str, encoding: str = "utf-8"):
        """کسی بھی فائل کو سیو کریں: projects/<project_name>/<relative_path>"""
        return save_file(self.project, relative_path, content, encoding)

    def list(self):
        """پروجیکٹ کی تمام فائلیں دکھائیں"""
        return list_project_files(self.project)
    
    def create_backend_structure(self):
        """خود بخود backend ڈھانچہ بنائیں"""
        structures = {
            "backend/app.py": "# Main Flask Application",
            "backend/models.py": "# Database Models", 
            "backend/routes.py": "# API Routes",
            "backend/config.py": "# Configuration",
            "backend/requirements.txt": "# Python Dependencies",
            "frontend/index.html": "<!DOCTYPE html>\n<html>\n<head>\n    <title>Agent50 App</title>\n</head>\n<body>\n    <h1>AGENT 50 Generated App</h1>\n</body>\n</html>",
            "README.md": "# AGENT 50 Project\n\nThis project was automatically generated by Agent50 - Super King DeepSeek"
        }
        
        results = []
        for path, content in structures.items():
            result = self.write(path, content)
            results.append(result)
        
        return results

# Global instance for Agent50
agent50_client = AgentFileClient("agent50")

def quick_test():
    """فوری ٹیسٹ کے لیے"""
    print("🧪 Testing Agent50 File Interface...")
    
    # ٹیسٹ فائل لکھیں
    result = agent50_client.write("test/test_file.py", "# Test file created by Agent50\nprint('Hello from Agent50!')")
    print(f"✅ File saved: {result}")
    
    # فہرست دیکھیں
    files = agent50_client.list()
    print(f"📁 Project files: {files}")
    
    return True

if __name__ == "__main__":
    quick_test()