import os
import subprocess
import json
from pathlib import Path

# --- CONFIGURATION ---
DEPLOY_STATE_FILE = "deploy_state.json"

class KingDeployer:
    def __init__(self, project_dir):
        self.project_dir = Path(project_dir)
        self.state_file = self.project_dir / DEPLOY_STATE_FILE
        self.state = self.load_state()

    def load_state(self):
        if self.state_file.exists():
            try:
                with open(self.state_file, 'r', encoding='utf-8') as f:
                    return json.load(f)
            except:
                pass
        return {
            "git_initialized": False,
            "docker_ready": False,
            "render_config_ready": False,
            "last_update": None
        }

    def save_state(self):
        with open(self.state_file, 'w', encoding='utf-8') as f:
            json.dump(self.state, f, indent=4)

    def run_command(self, command):
        """Runs a shell command inside the project directory."""
        try:
            print(f"  ⚡ Running: {command}")
            result = subprocess.run(
                command, 
                shell=True, 
                cwd=self.project_dir, 
                capture_output=True, 
                text=True,
                encoding='utf-8', 
                errors='replace'
            )
            if result.returncode == 0:
                print("    ✅ Success")
                return True, result.stdout
            else:
                print(f"    ❌ Failed: {result.stderr}")
                return False, result.stderr
        except Exception as e:
            return False, str(e)

    # --- GIT OPERATIONS ---
    def init_git(self):
        print(f"\n🐙 [GIT] Initializing Repository in {self.project_dir.name}...")
        
        # 1. Create .gitignore
        gitignore_content = """
.venv
__pycache__
*.pyc
instance/
*.db
.env
.DS_Store
"""
        with open(self.project_dir / ".gitignore", "w", encoding='utf-8') as f:
            f.write(gitignore_content.strip())
        
        # 2. Git Init
        if not (self.project_dir / ".git").exists():
            self.run_command("git init")
            self.state["git_initialized"] = True
        
        # 3. Add & Commit
        self.run_command("git add .")
        self.run_command('git commit -m "Initial commit by Agent 50 Supreme"')
        
        self.save_state()
        print("  ✅ Git Repository Ready.")

    # --- DEPLOYMENT CONFIGS ---
    def prepare_for_render(self):
        print(f"\n🚀 [RENDER] Preparing Deployment Assets...")
        
        # 1. Procfile (For Gunicorn)
        with open(self.project_dir / "Procfile", "w", encoding='utf-8') as f:
            f.write("web: gunicorn app:app")
        
        # 2. render.yaml (Infrastructure as Code)
        render_yaml = f"""
services:
  - type: web
    name: {self.project_dir.name}
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
"""
        with open(self.project_dir / "render.yaml", "w", encoding='utf-8') as f:
            f.write(render_yaml.strip())
            
        self.state["render_config_ready"] = True
        self.save_state()
        print("  ✅ Render Configuration Ready (Procfile + render.yaml).")

    # --- DOCUMENTATION ---
    def generate_guide(self):
        print(f"\n📘 [DOCS] Generating Deployment Guide...")
        
        guide = f"""
# 🚀 Deployment Guide: {self.project_dir.name}
Generated by Agent 50 Supreme

## 1. Git Setup
Your project is already a Git repository.
1. Create a repo on GitHub.
2. Link it: `git remote add origin https://github.com/YOUR_USERNAME/{self.project_dir.name}.git`
3. Push: `git push -u origin master`

## 2. Deploy to Render.com
1. Login to [Render](https://dashboard.render.com/).
2. Click **New +** -> **Web Service**.
3. Connect your GitHub repository.
4. Render will detect `render.yaml` or use these settings:
   - **Build Command:** `pip install -r requirements.txt`
   - **Start Command:** `gunicorn app:app`
5. Click **Create Web Service**.

## 3. Mobile App (Flutter)
1. Navigate to `mobile_app_flutter/`.
2. Run `flutter build apk` (Android).
3. Run `flutter build ipa` (iOS - requires Mac).
"""
        with open(self.project_dir / "README_DEPLOY.md", "w", encoding='utf-8') as f:
            f.write(guide)
        
        print("  ✅ README_DEPLOY.md Created.")

    # --- MAIN PIPELINE ---
    def execute_pipeline(self):
        print(f"🏗️ STARTING DEPLOYMENT PREP FOR: {self.project_dir.name}")
        self.init_git()
        self.prepare_for_render()
        self.generate_guide()
        print("👑 DEPLOYMENT PREP COMPLETE.")